[window]
# Opacity: 1.0 is fully opaque, 0.0 fully transparent.
# Requires a running compositor to see transparency.
opacity = 0.4

[font]
size = 10.0

[font.normal]
family = "monospace"

[colors.primary]
background = "0x000000"
foreground = "0x00aaff"

[colors.normal]
black   = "0x000000"
red     = "0xFF5555"
green   = "0x50FA7B"
yellow  = "0xF1FA8C"
blue    = "0xBD93F9"
magenta = "0xFF79C6"
cyan    = "0x8BE9FD"
white   = "0xBFBFBF"

[colors.bright]
black   = "0x4D4D4D"
red     = "0xFF6E67"
green   = "0x5AF78E"
yellow  = "0xF4F99D"
blue    = "0xCAA9FA"
magenta = "0xFF92D0"
cyan    = "0x9AEDFE"
white   = "0xE6E6E6"

