/*
 RequireJS domReady 2.0.1 Copyright (c) 2010-2012, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/requirejs/domReady for details
 MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors */
define("third_party/domready/domReady",[],function(){function d(){if(!f){f=!0;e&&clearInterval(e);var a=m;if(f&&a.length){m=[];var b;for(b=0;b<a.length;b+=1)a[b](l)}}}function b(a){f?a(l):m.push(a);return b}var c,a,e,g="undefined"!==typeof window&&window.document,f=!g,l=g?document:null,m=[];if(g){if(document.addEventListener)document.addEventListener("DOMContentLoaded",d,!1),window.addEventListener("load",d,!1);else if(window.attachEvent){window.attachEvent("onload",d);a=document.createElement("div");
try{c=null===window.frameElement}catch(h){}a.doScroll&&c&&window.external&&(e=setInterval(function(){try{a.doScroll(),d()}catch(b){}},30))}"complete"===document.readyState&&d()}b.version="2.0.1";b.load=function(a,c,d,e){e.isBuild?d(null):b(d)};return b});
define("qowtRoot/utils/typeUtils",[],function(){function d(a,b,d){if(d.types.every(function(a){var b=c[a];if(!b)throw Error("Bad config to checkArgTypes: unknown type: "+a);return!b(d.value)})){var f=1===d.types.length?d.types[0]:"["+d.types.join(",")+"]";throw Error("Argument "+b+" passed to function "+a+" was supposed to be of type "+f+" but had value "+d.value);}}var b={checkArgTypes:function(a,b){for(var c in b){var f={value:b[c][0],types:b[c].slice(1)};d(a,c,f)}},isObject:function(a){return"object"===
typeof a&&null!==a},isPromise:function(a){return a instanceof Promise},isPromiseLike:function(a){return!(!a||!b.isFunction(a.then))},isList:function(a){return"[object Array]"===Object.prototype.toString.call(a)},isNumber:function(a){return"number"===typeof a&&!isNaN(a)},isInteger:function(a){return"number"===typeof a&&parseInt(a,10)===a},isFunction:function(a){return"function"===typeof a},isString:function(a){return"[object String]"===Object.prototype.toString.call(a)},isRegex:function(a){return"[object RegExp]"===
Object.prototype.toString.call(a)},isNode:function(a){return a instanceof Node},isNull:function(a){return null===a},isUndefined:function(a){return void 0===a},isBoolean:function(a){return"boolean"===typeof a},getType:function(a){var b;Object.keys(c).forEach(function(d){c[d](a)&&(b=d)});return b},isArgumentsObjectOrList:function(a){return a instanceof Object&&a.hasOwnProperty("length")},extend:function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])},createNewType:function(a){var b=function(){},
d={isOfType:function(a){return void 0!==a&&null!==a&&a.constructor===b},markAsType:function(a){Object.defineProperty(a,"constructor",{value:b,configurable:!1,writable:!1,enumerable:!1});return a}};if(a){if(c[a])throw Error("Already registered type "+a);c[a]=d.isOfType}return d}},c={string:b.isString,object:b.isObject,promise:b.isPromise,promiseLike:b.isPromiseLike,node:b.isNode,regex:b.isRegex,"function":b.isFunction,number:b.isNumber,list:b.isList,boolean:b.isBoolean,"null":b.isNull,undefined:b.isUndefined};
return b});(function(){var d={},b=window.sessionStorage.getItem("featureOverrides");b&&(d=JSON.parse(b));d.isRelease=!0;d.edit=!1;window.sessionStorage.setItem("featureOverrides",JSON.stringify(d));window.localStorage.removeItem("testsToInclude");window.localStorage.removeItem("builtInTests")})();define("configs/releaseFeatures",function(){});
(function(){var d={},b=window.sessionStorage.getItem("featureOverrides");b&&(d=JSON.parse(b));d.save=!!(window.chrome&&window.chrome.fileSystem&&window.chrome.fileSystem.chooseEntry);window.sessionStorage.setItem("featureOverrides",JSON.stringify(d))})();define("configs/chromeFeatures",function(){});define("qowtRoot/features/pack",[],function(){return{edit:!0,save:!1,pointEdit:!1,hats:!0}});
define("qowtRoot/features/utils",["qowtRoot/features/pack"],function(d){var b={isEnabled:function(a){a=d[a];return void 0===a?!1:a},enable:function(a){d[a]=!0},disable:function(a){d[a]=!1},setOverrides:function(a){for(var b in a)a.hasOwnProperty(b)&&(d[b]=a[b])},isDebug:function(){return void 0!==c?c:!b.isEnabled("isRelease")},setDebugOverride:function(a){c=a},clearDebugOverride:function(){c=void 0}},c;return b});
(function(d){d("qowtRoot/third_party/when/lib/timer",["require"],function(b){return{set:setTimeout,clear:clearTimeout}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});
(function(d){d("qowtRoot/third_party/when/lib/timed",[],function(){return function(b,c,a){a.prototype.delay=function(a){var c=this;return new this.constructor(function(d,l,m){c.then(function(c){b(function(){d(c)},a)},l,m)})};a.prototype.timeout=function(a,d){var f=this,l=1<arguments.length;return new this.constructor(function(m,h,r){var n=b(function(){h(l?d:Error("timed out after "+a+"ms"))},a);f.then(function(a){c(n);m(a)},function(a){c(n);h(a)},r)})};return a}})})("function"===typeof define&&define.amd?
define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/array",[],function(){return function(b){var c=Array.prototype.map,a=Array.prototype.reduce,d=Array.prototype.reduceRight,g=Array.prototype.forEach,f=b.resolve,l=b.all;b.any=function(a){return new b(function(b,c){function d(a){l.push(a);0===--e&&c(l)}var e=0,l=[];g.call(a,function(a){++e;f(a).then(b,d)});0===e&&b()})};b.some=function(a,c){return new b(function(b,d,e){function l(a){0<k&&(--k,w.push(a),0===k&&b(w))}function v(a){0<t&&(--t,A.push(a),0===t&&
d(A))}var k=0,t,w=[],A=[];g.call(a,function(a){++k;f(a).then(l,v,e)});c=Math.max(c,0);t=k-c+1;k=Math.min(c,k);0===k&&b(w)})};b.settle=function(a){return l(c.call(a,function(a){function b(){return a.inspect()}a=f(a);return a.then(b,b)}))};b.map=function(a,b,d){return l(c.call(a,function(a){return f(a).then(b,d)}))};b.reduce=function(b,c){function d(a,b,e){return f(a).then(function(a){return f(b).then(function(b){return c(a,b,e)})})}return 2<arguments.length?a.call(b,d,arguments[2]):a.call(b,d)};b.reduceRight=
function(a,b){function c(a,d,e){return f(a).then(function(a){return f(d).then(function(c){return b(a,c,e)})})}return 2<arguments.length?d.call(a,c,arguments[2]):d.call(a,c)};b.prototype.spread=function(a){return this.then(l).then(function(b){return a.apply(void 0,b)})};return b}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/fatal",["require","./timer"],function(b){var c=b("./timer").set;return function(a){c(function(){throw a;},0)}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});
(function(d){d("qowtRoot/third_party/when/lib/flow",["require","./fatal"],function(b){function c(){throw new TypeError("catch predicate must be a function");}function a(a,b){return function(){a.call(this);return b}}function d(){}var g=b("./fatal");return function(b){function l(a,b){return function(c){return(b===Error||null!=b&&b.prototype instanceof Error?c instanceof b:b(c))?a.call(this,c):h(c)}}var m=b.resolve,h=b.reject,r=b.prototype["catch"];b.prototype.done=function(a,b){var c=this._handler;
c.when(this._maybeFatal,d,this,c.receiver,a,b)};b.prototype._maybeFatal=function(a){if(Object(a)===a)m(a)["catch"](this._fatal)};b.prototype._fatal=g;b.prototype["catch"]=b.prototype.otherwise=function(a){return 1===arguments.length?r.call(this,a):"function"!==typeof a?this.ensure(c):r.call(this,l(arguments[1],a))};b.prototype["finally"]=b.prototype.ensure=function(b){if("function"!==typeof b)return this;b=a(b,this);return this.then(b,b)};b.prototype["else"]=b.prototype.orElse=function(a){return this.then(void 0,
function(){return a})};b.prototype.yield=function(a){return this.then(function(){return a})};b.prototype.tap=function(a){return this.then(a).yield(this)};return b}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});(function(d){d("qowtRoot/third_party/when/lib/inspect",[],function(){return function(b){b.prototype.inspect=function(){return this._handler.inspect()};return b}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/iterate",[],function(){return function(b){function c(a,b,l,m){function h(h){return d(l(h)).then(function(){return c(a,b,l,a(h))})}return d(m).then(function(a){return d(b(a)).then(function(b){return b?a:h(a)})})}function a(b,c,l,m){function h(h,m){return d(l(h)).then(function(){return a(b,c,l,m)})}return d(m).then(function(a){return d(c(a)).then(function(c){return c?a:d(b(a)).spread(h)})})}var d=b.resolve;b.iterate=c;b.unfold=a;return b}})})("function"===
typeof define&&define.amd?define:function(d){module.exports=d()});(function(d){d("qowtRoot/third_party/when/lib/progress",[],function(){return function(b){b.prototype.progress=function(b){return this.then(void 0,void 0,b)};return b}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/with",[],function(){return function(b){b.prototype["with"]=b.prototype.withThis=b.prototype._bindContext;return b}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/makePromise",[],function(){return function(b){function c(b){var c=this;this._handler=new n;a(b,function(a){c._handler.resolve(a)},function(a){c._handler.reject(a)},function(a){c._handler.notify(a)})}function a(a,b,c,d){try{a(b,c,d)}catch(e){c(e)}}function d(a){return new g(new z(new t(a)))}function g(a){this._handler=a}function f(a,b){if(a instanceof c){var d=a._handler.join();return b===d?new t(new TypeError("Promise cycle")):d}return D(a)?m(a):new k(a)}
function l(a){return a instanceof c?a._handler.join():m(a)}function m(a){try{var b=a.then;return"function"===typeof b?new v(b,a):new k(a)}catch(c){return new t(c)}}function h(){}function r(a){this.handler=a;if(this._isMonitored()){var b=this._env.promiseMonitor.captureStack();this.trace=a._addTrace(b)}}function n(a){this.consumers=[];this.receiver=a;this.handler=void 0;this.resolved=!1;this._isMonitored()&&(this.trace=this._env.promiseMonitor.captureStack())}function z(a){r.call(this,a)}function B(a,
b){r.call(this,a);this.receiver=b}function v(a,b){n.call(this);this.assimilated=!1;this.untrustedThen=a;this.thenable=b}function k(a){this.value=a}function t(a){this.value=a;this.observed=!1;this._isMonitored()&&(this.key=this._env.promiseMonitor.startTrace(a))}function w(){return{state:"pending"}}function A(a,b,c,d,e,p,g,l){this.a=a;this.b=b;this.c=c;this.d=d;this.e=e;this.f=p;this.g=g;this.handler=l}function E(a,b){this.q=a;this.value=b}function D(a){return("object"===typeof a||"function"===typeof a)&&
null!==a}function H(a,b,c){try{return a.call(c,b)}catch(g){return d(g)}}function x(){}var C,y=b.scheduler,u=Object.create||function(a){function b(){}b.prototype=a;return new b};c.resolve=function(a){return a instanceof c?a:new g(new z(f(a)))};c.reject=d;c.never=function(){return C};c._defer=function(){return new g(new n)};c.prototype.then=function(a,b,c){var d=this._handler,e=new n(d.receiver);d.when(e.resolve,e.notify,e,d.receiver,a,b,c);return new g(e)};c.prototype["catch"]=c.prototype.otherwise=
function(a){return this.then(void 0,a)};c.prototype._bindContext=function(a){return new g(new B(this._handler,a))};c.all=function(a){function b(a,c,d,p){d.when(x,x,void 0,a,function(a){c[p]=a;0===--e&&this.resolve(c)},a.reject,a.notify)}var c=new n,d=a.length>>>0,e=d,p=[],f,h;for(f=0;f<d;++f)f in a?(h=a[f],D(h)?b(c,p,l(h),f):(p[f]=h,--e)):--e;0===e&&c.resolve(p);return new g(c)};c.race=function(a){if(Object(a)===a&&0===a.length)return C;for(var b=new n,c=0;c<a.length;++c)f(a[c]).when(x,x,void 0,b,
b.resolve,b.reject);return new g(b)};g.prototype=u(c.prototype);h.prototype.inspect=w;h.prototype.when=x;h.prototype.resolve=x;h.prototype.reject=x;h.prototype.notify=x;h.prototype.join=function(){return this};h.prototype._env=b.monitor||c;h.prototype._addTrace=x;h.prototype._isMonitored=function(){return"undefined"!==typeof this._env.promiseMonitor};r.prototype=u(h.prototype);r.prototype.join=function(){return this.handler.join()};r.prototype.inspect=function(){return this.handler.inspect()};r.prototype._addTrace=
function(a){return this.handler._addTrace(a)};n.prototype=u(h.prototype);n.prototype.inspect=function(){return this.resolved?this.handler.join().inspect():w()};n.prototype.resolve=function(a){this._join(f(a,this))};n.prototype.reject=function(a){this._join(new t(a))};n.prototype.join=function(){return this.resolved?this.handler.join():this};n.prototype.run=function(){var a=this.consumers,b=this.handler=this.handler.join();this.consumers=void 0;for(var c=0;c<a.length;c+=7)b.when(a[c],a[c+1],a[c+2],
a[c+3],a[c+4],a[c+5],a[c+6])};n.prototype._join=function(a){this.resolved||(this.resolved=!0,this.handler=a,y.enqueue(this),this._isMonitored()&&(this.trace=a._addTrace(this.trace)))};n.prototype.when=function(a,b,c,d,e,p,g){this.resolved?y.enqueue(new A(a,b,c,d,e,p,g,this.handler.join())):this.consumers.push(a,b,c,d,e,p,g)};n.prototype.notify=function(a){this.resolved||y.enqueue(new E(this.consumers,a))};n.prototype._addTrace=function(a){return this.resolved?this.handler._addTrace(a):a};z.prototype=
u(r.prototype);z.prototype.when=function(a,b,c,d,e,p,g){y.enqueue(new A(a,b,c,d,e,p,g,this.join()))};B.prototype=u(r.prototype);B.prototype.when=function(a,b,c,d,e,p,g){void 0!==this.receiver&&(d=this.receiver);this.join().when(a,b,c,d,e,p,g)};v.prototype=u(n.prototype);v.prototype.when=function(a,b,c,d,e,p,g){this.assimilated||(this.assimilated=!0,this._assimilate());n.prototype.when.call(this,a,b,c,d,e,p,g)};v.prototype._assimilate=function(){var a=this;this._try(this.untrustedThen,this.thenable,
function(b){a.resolve(b)},function(b){a.reject(b)},function(b){a.notify(b)})};v.prototype._try=function(a,b,c,d,e){try{a.call(b,c,d,e)}catch(p){d(p)}};k.prototype=u(h.prototype);k.prototype.inspect=function(){return{state:"fulfilled",value:this.value}};k.prototype.when=function(a,b,c,d,e){b="function"===typeof e?H(e,this.value,d):this.value;a.call(c,b)};t.prototype=u(h.prototype);t.prototype.inspect=function(){return{state:"rejected",reason:this.value}};t.prototype.when=function(a,b,c,g,f,p){this._isMonitored()&&
!this.observed&&this._env.promiseMonitor.removeTrace(this.key);this.observed=!0;b="function"===typeof p?H(p,this.value,g):d(this.value);a.call(c,b)};t.prototype._addTrace=function(a){this.observed||this._env.promiseMonitor.updateTrace(this.key,a)};C=new g(new h);A.prototype.run=function(){this.handler.when(this.a,this.b,this.c,this.d,this.e,this.f,this.g)};E.prototype.run=function(){for(var a=this.q,b=1;b<a.length;b+=7)this._notify(a[b],a[b+1],a[b+2],a[b+5])};E.prototype._notify=function(a,b,c,d){var e;
if("function"===typeof d)try{e=d.call(c,this.value)}catch(p){e=p}else e=this.value;a.call(b,e)};return c}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/Queue",[],function(){function b(b){this.head=this.tail=this.length=0;this.buffer=Array(1<<b)}b.prototype.push=function(b){this.length===this.buffer.length&&this._ensureCapacity(2*this.length);this.buffer[this.tail]=b;this.tail=this.tail+1&this.buffer.length-1;++this.length;return this.length};b.prototype.shift=function(){var b=this.buffer[this.head];this.buffer[this.head]=void 0;this.head=this.head+1&this.buffer.length-1;--this.length;return b};b.prototype._ensureCapacity=
function(b){var a=this.head,d=this.buffer,g=Array(b),f=0,l;if(0===a)for(l=this.length;f<l;++f)g[f]=d[f];else{b=d.length;for(l=this.tail;a<b;++f,++a)g[f]=d[a];for(a=0;a<l;++f,++a)g[f]=d[a]}this.buffer=g;this.head=0;this.tail=this.length};return b})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/scheduler",["require","./Queue"],function(b){function c(b){this._enqueue=b;this._handlerQueue=new a(15);var c=this;this.drainQueue=function(){c._drainQueue()}}var a=b("./Queue");c.prototype.enqueue=function(a){1===this._handlerQueue.push(a)&&this._enqueue(this.drainQueue)};c.prototype._drainQueue=function(){for(var a=this._handlerQueue;0<a.length;)a.shift().run()};return c})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});
(function(d){d("qowtRoot/third_party/when/lib/async",["require"],function(b){var c;return"undefined"!==typeof process&&null!==process&&"function"===typeof process.nextTick?function(a){process.nextTick(a)}:(c="function"===typeof MutationObserver&&MutationObserver||"function"===typeof WebKitMutationObserver&&WebKitMutationObserver)?function(a,b){var c,d=a.createElement("div");(new b(function(){var a=c;c=void 0;a()})).observe(d,{attributes:!0});return function(a){c=a;d.setAttribute("class","x")}}(document,
c):function(a){var b=setTimeout;return function(a){b(a,0)}}(b)})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});(function(d){d("qowtRoot/third_party/when/lib/Promise",["require","./makePromise","./scheduler","./async"],function(b){var c=b("./makePromise"),a=b("./scheduler");b=b("./async");return c({scheduler:new a(b),monitor:"undefined"!==typeof console?console:void 0})})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});
(function(d){d("qowtRoot/third_party/when/when","require ./lib/timer ./lib/timed ./lib/array ./lib/flow ./lib/inspect ./lib/iterate ./lib/progress ./lib/with ./lib/Promise".split(" "),function(b){function c(a,b,c,d){var e=t(a);return 2>arguments.length?e:e.then(b,c,d)}function a(a){return function(){return g(a,this,w.call(arguments))}}function d(a){return g(a,this,w.call(arguments,1))}function g(a,b,c){return k.all(c).then(function(c){return a.apply(b,c)})}function f(){function a(b){d._handler.resolve(b)}
function b(a){d._handler.reject(a)}function c(a){d._handler.notify(a)}var d=k._defer();this.promise=d;this.resolve=a;this.reject=b;this.notify=c;this.resolver={resolve:a,reject:b,notify:c}}var l=b("./lib/timer"),m=b("./lib/timed"),h=b("./lib/array"),r=b("./lib/flow"),n=b("./lib/inspect"),z=b("./lib/iterate"),B=b("./lib/progress"),v=b("./lib/with"),k=b("./lib/Promise"),k=[h,r,z,B,n,v].reduceRight(function(a,b){return b(a)},m(l.set,l.clear,k)),t=k.resolve,w=Array.prototype.slice;c.promise=function(a){return new k(a)};
c.resolve=k.resolve;c.reject=k.reject;c.lift=a;c["try"]=d;c.attempt=d;c.iterate=k.iterate;c.unfold=k.unfold;c.join=function(){return k.all(arguments)};c.all=function(a){return c(a,k.all)};c.settle=function(a){return c(a,k.settle)};c.any=a(k.any);c.some=a(k.some);c.map=function(a,b){return c(a,function(a){return k.map(a,b)})};c.reduce=function(a,b){var d=w.call(arguments,1);return c(a,function(a){d.unshift(a);return k.reduce.apply(k,d)})};c.reduceRight=function(a,b){var d=w.call(arguments,1);return c(a,
function(a){d.unshift(a);return k.reduceRight.apply(k,d)})};c.isPromiseLike=function(a){return a&&"function"===typeof a.then};c.Promise=k;c.defer=function(){return new f};return c})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});
define("qowtRoot/utils/promiseUtils",["qowtRoot/utils/typeUtils","qowtRoot/third_party/when/when"],function(d,b){var c={cast:function(a){return a instanceof Promise?a:Promise.resolve(a)},delay:function(a,b){a=a||0;return new Promise(function(c){setTimeout(c.bind(void 0,b),a)})},delayThenReject:function(a,b){a=a||0;return new Promise(function(c,d){setTimeout(d.bind(c,b),a)})},throwAndEscapeChain:function(a){a instanceof Error||(console.error("throwAndEscapeChain wrapping value in new Error: ",a),a=
Error(a));b.reject(a).done();throw a;},pipeline:function(a){function b(){for(var f=Array.prototype.slice.call(arguments,0);0<a.length;){var m=a.shift();if(d.isPromiseLike(m))return c.cast(m).then(function(c){a.unshift(c);return b.apply(g,f)});d.checkArgTypes("PromiseUtils.pipeline",{task:[m,"function"]});m=m.apply(g,f);if(d.isPromiseLike(m))return c.cast(m).then(function(a){return b(a)});f=[m]}return f[0]}var g=this,f=Array.prototype.slice.call(arguments,0);if(f.some(d.isPromiseLike))return Promise.all(f).then(function(a){return c.pipeline.apply(g,
a)});d.checkArgTypes("PromiseUtils.pipeline",{tasks:[a,"list"]});a=a.slice(0);return b.apply(g,f.slice(1))},finally:function(a,b){function d(){return c.cast(b()).then(function(){return a})}return c.cast(a).then(d,d)},waitForNextMacroTurn:function(a){return new Promise(function(b){window.setTimeout(b.bind(null,a),0)})}};return c});
define("qowtRoot/utils/platform",[],function(){var d=Object.create(Object.prototype,{name:{get:function(){return b}},locale:{get:function(){return c}},isOther:{get:function(){return"OTHER"===b}},isUnix:{get:function(){return"UNIX"===b}},isWindows:{get:function(){return"WINDOWS"===b}},isOsx:{get:function(){return"OSX"===b}},isLinux:{get:function(){return"LINUX"===b}},isCros:{get:function(){return"CROS"===b}}}),b,c;(function(){b="OTHER";var a=navigator.appVersion.toLowerCase();-1!==a.indexOf("x11")&&
(b="UNIX");-1!==a.indexOf("win")&&(b="WINDOWS");-1!==a.indexOf("mac")&&(b="OSX");-1!==a.indexOf("linux")&&(b="LINUX");-1!==a.indexOf("cros")&&(b="CROS");c=navigator.language.toUpperCase()})();return d});
define("utils/analytics/googleAnalytics",["qowtRoot/features/utils","qowtRoot/utils/promiseUtils","qowtRoot/utils/platform"],function(d,b,c){function a(a,b){var c;void 0!==y?c=y?Promise.resolve():Promise.reject(Error("ga permission cached (not permitted)")):(chrome&&chrome.metricsPrivate&&chrome.metricsPrivate.getIsCrashReportingEnabled&&(!d.isDebug()||void 0!==window.__gaMock)?c=Promise.resolve():(console.warn("GA not supported on this platform"),c=Promise.reject(Error("GA not supported on this platform"))),
c=c.then(e).catch(l));return c.then(m).then(a.bind(null,b)).catch(function(){})}function e(){var a=Error("Crash reporting setting timed out");return Promise.race([g(),b.delayThenReject(1E3,a)]).then(f)}function g(){return new Promise(function(a){chrome.metricsPrivate.getIsCrashReportingEnabled(a)})}function f(a){return new Promise(function(b,c){window.__gaMock&&(u=window.__gaMock.ga4TestUpdate(x));(y=a)?b():(console.warn("Crash reporting not allowed"),c())})}function l(){y=!1;return Promise.reject()}
function m(){void 0===F&&h("QO");return Promise.resolve()}function h(a){if(F=a)G=a,r(G);window.__gaMock&&u.setTracker(D[a]);return Promise.resolve()}function r(a){C!==a&&(G=C=a,window.__gaMock&&u.sendState(a),v({name:"page_view"}));return Promise.resolve()}function n(a){var b={name:"exception",parameters:{}};b.parameters.description=a.msg;b.parameters.fatal=a.fatal;window.__gaMock&&u.sendException(a.msg,a.fatal);v(b);return Promise.resolve()}function z(a){if(6E4>=a.value)return"Percentile99th";if(6E4<
a.value&&12E5>=a.value)return"Percentile99.90th";if(12E5<a.value)return"Percentile99.99th"}function B(a){window.__gaMock&&(t(),u.sendEvent(a.category,a.action,q));v(a);return Promise.resolve()}function v(a){var b=D[F],c=H[F];a.name=a.name?a.name:a.action;A().then(function(d){try{fetch(E+"?measurement_id="+b+"&api_secret="+c,{method:"POST",body:JSON.stringify({client_id:d,timestamp_micros:1E3*(new Date).getTime(),events:[w(a)]})})}catch(e){console.error("Google Analytics request failed with an exception",
e)}})}function k(a){if("10.0"===a)return"10";if("6.2"===a)return"8";if("6.1"===a)return"7";if("6.0"===a)return"Vista";if("5.1"===a)return"XP";if("5.0"===a)return"2000";a}function t(){if(!q){q={engagement_time_msec:100};q.session_id=window.__gaMock?"":J;q.app_version=window.__gaMock?"":chrome.runtime.getManifest().version;q.user_language=c.locale;q.operating_system="LINUX"===c.name?"Linux":"WINDOWS"===c.name?"Windows":"CROS"===c.name?"Chrome OS":"OSX"===c.name?"Macintosh":c.name;q.screen_resolution=
window.screen.width+"x"+window.screen.height;q.viewport=window.innerWidth+"x"+window.innerHeight;var a=q,b,d=/\(([^)]+)\)/.exec(navigator.userAgent)[1];c.isCros&&-1!==d.indexOf("CrOS")?b=d.match(/CrOS.*\d+(?:\.\d+)+/)[0].replace("CrOS ",""):c.isLinux&&-1!==d.indexOf("Linux")?b=/[^ ]*$/.exec(d)[0]:c.isOsx&&-1!==d.indexOf("Mac OS X")?(b=d.match(/\d+[._]\d+(?:[._]\d+)?/)[0].replaceAll("_","."),1<b.match(/\./g).length&&(b=b.match(/^(\d+\.\d+)/)[0])):c.isWindows&&-1!==d.indexOf("Windows")&&(b=d.match(/\d+(?:\.\d+)+/)[0],
b=k(b));a.operating_system_version=b;q.app_name=x}}function w(a){var b=a.name.replaceAll("-","_");t();q.page_title=G;"CC"===a.action&&"performance-metrics"===a.category?q.percentile_type=z(a):"CR"===a.action&&"performance-metrics"===a.category&&(q.percentile_type=z(a));if(!a.parameters||"exception"!==a.name&&"page_view"!==a.name)q.event_category=a.category,a.label&&(q.event_label=a.label),a.value&&(q.value=a.value);else for(var c=Object.keys(a.parameters),d=0;d<c.length;d++)q[c[d]]=a.parameters[c[d]];
return{name:b,params:q}}function A(){I||(I=new Promise(function(a,b){chrome.storage.sync.get("clientId",function(c){if(chrome.runtime.lastError)b(chrome.runtime.lastError);else if("undefined"===typeof c.clientId){var d=self.crypto.randomUUID();c={};c.clientId=d;chrome.storage.sync.set(c,function(){a(d)})}else a(c.clientId)})}));return I}var E="https://www.google-analytics.com/mp/collect",D={word:"G-2EHQ55R09Q",sheet:"G-429ETHTJYR",point:"G-5VSRBT2L9W",QO:"G-11BCJ4LWCJ"},H={word:"esgLzn1kRb6eHxjysYicgQ",
sheet:"v9vcbIqZSe6pTYEryGsfUQ",point:"5uHsbBE-Q3-tHRTfVqEEXg",QO:"k2-sQUVpTZWoDAUgoGUwog"},x="Quickoffice",C,y,u,J,F,G,q,I;return{setFileExt:function(a){},setSessionGroup:function(a){J=a},setTracker:function(b){return a(h,b)},sendState:function(b){return a(r,b)},sendException:function(b){return a(n,b)},sendEvent:function(b){return a(B,b)},getMeasurementId:function(a){return D[a]},reset:function(){G=F=u=y=C=void 0}}});
define("qowtRoot/utils/i18n",["qowtRoot/utils/typeUtils","utils/analytics/googleAnalytics"],function(d,b){var c={getMessage:function(a,b){var g="????";if(!chrome||!chrome.i18n)return a;d.isString(a)?(g=chrome.i18n.getMessage(a,b),g||(g=a,c.logError_("Missing translation",a))):c.logError_("Invalid string translation Id",a);return g},logError_:function(a,c){console.error(a+" "+c);b.sendException({msg:a,fatal:!1})}};return c});
require(["third_party/domready/domReady!"],function(){require(["qowtRoot/utils/i18n"],function(d){var b=d.getMessage("extension_popup_new_document_header");document.getElementById("newHeading").textContent=b;var b=d.getMessage("extension_popup_new_spreadsheet_document"),b=createOption(b,"sheet"),c=d.getMessage("extension_popup_new_presentation_document"),c=createOption(c,"point"),a=d.getMessage("extension_popup_new_word_document"),a=createOption(a,"word"),e=document.getElementById("options");e.appendChild(b);
e.appendChild(c);e.appendChild(a);document.getElementById("messageBody").innerHTML=d.getMessage("extension_popup_message_body")})});function createOption(d,b){var c=document.createElement("div");c.id=b;c.textContent=d;var a=document.createElement("a");a.textContent=d;a.href="#";c.addEventListener("click",onClick,!0);return c}
function onClick(d){var b;"word"===d.target.id?b="application/vnd.openxmlformats-officedocument.wordprocessingml.document":"point"===d.target.id?b="application/vnd.openxmlformats-officedocument.presentationml.presentation":"sheet"===d.target.id&&(b="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");chrome.windows.getCurrent(function(c){chrome.runtime.sendMessage({newCreate:d.target.id,mimeType:b,currentWindowId:c.id},function(){window.close()})})}define("mainPopup",function(){});
