// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1734541222);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1734541222);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.region-update-timer", 1734541222);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1734541222);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1734541252);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1734541222);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{6d4518a6-908d-4056-b0af-95616b1d1768}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.migration.version", 150);
user_pref("browser.newtabpage.activity-stream.impressionId", "{6effa0c4-d7b4-4820-b4e6-0955c63b117c}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1734541313898");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1734562913898");
user_pref("browser.search.serpEventTelemetryCategorization.regionEnabled", false);
user_pref("browser.startup.lastColdStartupCheck", 1734541196);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\",\"PersonalToolbar\"],\"currentVersion\":20,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "133.0.3");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 36);
user_pref("extensions.formautofill.creditCards.reauth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECMtmvNrIpRhnBAhA1wB1+M8UdQ==");
user_pref("extensions.lastAppBuildId", "20241211112127");
user_pref("extensions.lastAppVersion", "133.0.3");
user_pref("extensions.lastPlatformVersion", "133.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.quarantinedDomains.list", "autoatendimento.bb.com.br,ibpf.sicredi.com.br,ibpj.sicredi.com.br,internetbanking.caixa.gov.br,www.ib12.bradesco.com.br,www2.bancobrasil.com.br");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"9ac32545-6175-441d-b6f9-b6efb5e95b49\",\"pictureinpicture@mozilla.org\":\"14027034-22e6-4bc2-86f3-f83ff8eac630\",\"screenshots@mozilla.org\":\"a7d5796e-d310-4375-9819-e9dd115aa5e4\",\"webcompat-reporter@mozilla.org\":\"b761f7d2-0d61-4620-bb76-323fd352556b\",\"webcompat@mozilla.org\":\"e7143ecb-c8ca-478b-aa69-d94546f7c94a\",\"default-theme@mozilla.org\":\"ff231176-80a1-4035-9a6a-d4d3eafcc266\",\"{8ff2d753-2dc8-46de-a837-fa28331d9fcf}\":\"72f93e96-77ad-453a-a929-89563ac53fcf\",\"addons-search-detection@mozilla.com\":\"c0a6745d-82f1-466e-81b1-5159e9a13c39\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.hashValue", "53a58bfb4c8124ad4f7655b99bfdea290033a085e0796b19245b33b91c0948fdac9f0c3e817130b352493a65d9a7a0fc8a7c1eedc618cdaa2b4580734a11cd9c");
user_pref("media.gmp-gmpopenh264.lastDownload", 1734541238);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1734541238);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1734541238);
user_pref("media.gmp-gmpopenh264.version", "2.3.2");
user_pref("media.gmp-manager.buildID", "20241211112127");
user_pref("media.gmp-manager.lastCheck", 1734541238);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs2", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("services.settings.blocklists.addons-bloomfilters.last_check", 1734541219);
user_pref("services.settings.blocklists.gfx.last_check", 1734541219);
user_pref("services.settings.clock_skew_seconds", 2);
user_pref("services.settings.last_update_seconds", 1734541219);
user_pref("services.settings.main.addons-manager-settings.last_check", 1734541219);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1734541219);
user_pref("services.settings.main.devtools-devices.last_check", 1734541219);
user_pref("services.settings.main.doh-config.last_check", 1734541219);
user_pref("services.settings.main.doh-providers.last_check", 1734541219);
user_pref("services.settings.main.fingerprinting-protection-overrides.last_check", 1734541219);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1734541219);
user_pref("services.settings.main.hijack-blocklists.last_check", 1734541219);
user_pref("services.settings.main.language-dictionaries.last_check", 1734541219);
user_pref("services.settings.main.message-groups.last_check", 1734541219);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1734541219);
user_pref("services.settings.main.partitioning-exempt-urls.last_check", 1734541219);
user_pref("services.settings.main.password-recipes.last_check", 1734541219);
user_pref("services.settings.main.public-suffix-list.last_check", 1734541219);
user_pref("services.settings.main.query-stripping.last_check", 1734541219);
user_pref("services.settings.main.search-config-icons.last_check", 1734541219);
user_pref("services.settings.main.search-config-overrides-v2.last_check", 1734541219);
user_pref("services.settings.main.search-config-v2.last_check", 1734541219);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1734541219);
user_pref("services.settings.main.sites-classification.last_check", 1734541219);
user_pref("services.settings.main.top-sites.last_check", 1734541219);
user_pref("services.settings.main.translations-wasm.last_check", 1734541219);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1734541219);
user_pref("services.settings.main.urlbar-persisted-search-terms.last_check", 1734541219);
user_pref("services.sync.engine.addresses.available", true);
user_pref("sidebar.backupState", "{\"width\":\"\",\"command\":\"\"}");
user_pref("signon.management.page.os-auth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECBMJ0fwoTQ0wBAjAP+79aykDhg==");
user_pref("toolkit.startup.last_success", 1734541190);
user_pref("toolkit.telemetry.cachedClientID", "9fec5756-4023-4dc6-8e07-b88acbe00751");
user_pref("toolkit.telemetry.cachedProfileGroupID", "2041ef32-cacd-452b-a786-a48528da14be");
user_pref("toolkit.telemetry.previousBuildID", "20241211112127");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
